# Generated by Django 4.2.2 on 2023-06-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
    ]
